$(info ==> opensbi-custom.mk)

OPENSBI_CUSTOM_PLATFORM_NAME   = $(BR2_PACKAGE_OPENSBI_CUSTOM_PLATFORM_NAME)
OPENSBI_CUSTOM_PLATFORM_DIR    = $(BR2_PACKAGE_OPENSBI_CUSTOM_PLATFORM_DIR)
$(info BR2_PACKAGE_OPENSBI_CUSTOM_PLATFORM_NAME $(BR2_PACKAGE_OPENSBI_CUSTOM_PLATFORM_NAME))

OPENSBI_MAKE_ENV += PLATFORM_DIR=$(BR2_PACKAGE_OPENSBI_CUSTOM_PLATFORM_DIR)
#CROSS_COMPILE="$(TARGET_CROSS)" \
# PLATFORM=$(BR2_PACKAGE_OPENSBI_CUSTOM_PLATFORM_NAME) \
# FW_DYNAMIC=y 

# Standard Buildroot package hook
$(eval $(generic-package))


